app:
    resource: "@AppBundle/Controller/"
    type:     annotation

lucky_number:
    path: /lucky/number
    defaults: { _controller: AppBundle:Lucky:number}

plus_image:
    path: /plus.{_format}
    defaults: { _controller: AppBundle:Default:plusImage, _format: png }
    requirements:
        _format: png

user_check:
    path: /userCheck
    defaults: { _controller: AppBundle:Default:userCheck }

objects_entry:
    path: /objects/entry.{_format}
    defaults: { _controller: AppBundle:Objects:entry, _format: js }
    requirements:
        _format: js

objects_person:
    path: /objects/person.{_format}
    defaults: { _controller: AppBundle:Objects:person, _format: js }
    requirements:
        _format: js

termbase_list:
    path: /termbase
    defaults: { _controller: AppBundle:Default:termbase }

create_termbase:
    path: /termbase/create
    defaults: { _controller: AppBundle:TermbaseEdit:create }

import_termbase:
    path: /termbase/import
    defaults: { _controller: AppBundle:TermbaseEdit:import }

import_view_termbase:
    path: /termbase/importView
    defaults: { _controller: AppBundle:TermbaseEdit:importView }

create_termbase_js:
    path: /termbase/create.{_format}
    defaults: { _controller: AppBundle:TermbaseEdit:script, _format: js }
    requirements:
        _format: js|json

save_termbase:
    path: /termbase/save
    defaults: { _controller: AppBundle:TermbaseEdit:save }

delete_termbase:
    path: /termbase/delete
    defaults: { _controller: AppBundle:TermbaseEdit:delete }

export_termbase:
    path: /termbase/export
    defaults: { _controller: AppBundle:TermbasesSelect:export }
    requirements:
        _method:  GET

search_termbase:
    path: /termbase/search
    defaults: { _controller: AppBundle:TermbaseSearch:search }

search_termbase:
    path: /termbase/search_all
    defaults: { _controller: AppBundle:TermbaseSearch:searchAll }

search_termbase_js:
    path: /termbase/search.{_format}
    defaults: { _controller: AppBundle:TermbaseSearch:script, _format: js}
    requirements:
        _format: js|json

search_termbase_js:
    path: /termbase/search_all.{_format}
    defaults: { _controller: AppBundle:TermbaseSearch:scriptAll, _format: js}
    requirements:
        _format: js|json

lang_codes_list:
    path: /termbase/lang_codes.{_format}
    defaults: { _controller: AppBundle:TermbaseSearch:langJsonLoad, _format: json}
    requirements:
        _format: js|json

region_codes_list:
    path: /termbase/region_codes.{_format}
    defaults: { _controller: AppBundle:TermbaseSearch:regionJsonLoad, _format: json}
    requirements:
        _format: js|json

jbox_small:
    path: /termbase/entry/view/small
    defaults: { _controller: JboxBundle:Jbox:small }

jbox_large:
    path: /termbase/entry/view/large
    defaults: { _controller: JboxBundle:Jbox:large }

jbox_addNote:
    path: /termbase/entry/view/addNote
    defaults: { _controller: JboxBundle:Jbox:addNote }

entry_get:
    path: /termbase/entry/get
    defaults: { _controller: AppBundle:EditEntry:get }

entry_save_page:
    path: /termbase/entry/savePage
    defaults: { _controller: AppBundle:EditEntry:savePageView }

entry_update:
    path: /termbase/entry/update
    defaults: { _controller: AppBundle:EditEntry:update }

entry_delete:
    path: /termbase/entry/delete
    defaults: { _controller: AppBundle:EditEntry:delete }

entry_upload:
    path: /termbase/entry/upload
    defaults: { _controller: AppBundle:EditEntry:upload }

entry_new:
    path: /termbase/entry/new
    defaults: { _controller: AppBundle:EditEntry:new }

entry_new_entry:
    path: /termbase/entry/new/entry
    defaults: { _controller: AppBundle:EditEntry:entry }

entry_new_lang:
    path: /termbase/entry/new/lang
    defaults: { _controller: AppBundle:EditEntry:lang }

entry_new_term:
    path: /termbase/entry/new/term
    defaults: { _controller: AppBundle:EditEntry:term }

entry_new_ext_ref:
    path: /termbase/entry/new/ext_ref
    defaults: { _controller: AppBundle:EditEntry:extRef }

entry_term_geo:
    path: /termbase/entry/term/geo
    defaults: { _controller: AppBundle:EditEntry:geo }

entry_new_image:
    path: /termbase/entry/new/image
    defaults: { _controller: AppBundle:EditEntry:image }

search_termbase_mini:
    path: /termbase/search/mini
    defaults: { _controller: AppBundle:TermbaseSearch:miniSearch }

language_quick_select:
    path: /termbase/entry/new/term/selectLanguage
    defaults: { _controller: AppBundle:EditEntry:quickLangSelect }

tablesorter_bg:
    path: /css/bg.{_format}
    defaults: { _controller: AppBundle:TablesorterCSS:bg, _format: gif }
    requirements:
        _format: gif

tablesorter_asc:
    path: /css/asc.{_format}
    defaults: { _controller: AppBundle:TablesorterCSS:asc, _format: gif }
    requirements:
        _format: gif

tablesorter_desc:
    path: /css/desc.{_format}
    defaults: { _controller: AppBundle:TablesorterCSS:desc, _format: gif }
    requirements:
        _format: gif

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

login:
    path: /login

register:
    path: /register

logout:
    path: /logout

manage_users:
    path: /users
    defaults: { _controller: AppBundle:UserEdit:view }

user_role_edit:
    path: /users/user_role
    defaults: { _controller: AppBundle:UserEdit:roleUpdate }

user_personId_edit:
    path: /users/personId
    defaults: { _controller: AppBundle:UserEdit:setPersonId }

user_person_add:
    path: /users/add_person
    defaults: { _controller: AppBundle:UserEdit:addPerson }